### ISSUE TITLE
1.0 Checklist

### ISSUE THREAD

**Issue by MSeal** [nteract/papermill#195]
It's getting closer to the time where we should make papermill version 1.0. I wanted to gather feedback on features, decisions, and other requirements for us to promote out of the 0 versions.

These are the few I think we should be adding for 1.0 release at some point in the future:
- [x] [90%+ test coverage](https://github.com/nteract/papermill/issues/46)
- [x] [--engine support](https://github.com/nteract/papermill/issues/177)
- [x] clear direction for [record pattern](https://github.com/nteract/papermill/issues/175) in the future (possible with deprecation tag on record method)
- [x] [Better OOM crash experience](https://github.com/nteract/papermill/issues/125)
- [x] More languages / kernels supported (open to suggestions on what we consider good coverage of options here)

We could discuss and tag issues we want to be considered fully stable. Other ideas / concerns?

**Comment by MSeal** [comment]
Added:
- [] [IO Dependency Isolation](https://github.com/nteract/papermill/issues/257)

**Comment by MSeal** [comment]
With nbconvert 5.5 releasing, we'll have everything in this list done!
